name: Notify Home Repo of New Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update in Home Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HOME_REPO_PAT }}
          repository: teamajayji/home
          event-type: new_release
          client-payload: '{"version": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
